services:
  - type: static_site
    name: shramik
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_USE_DUMMY_OTP
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
